_wandb:
    value:
        cli_version: 0.21.1
        e:
            mk87whbia4e9llaf4nf5scacaazxpbch:
                codePath: New Data\SNN_Manual.ipynb
                codePathLocal: SNN_Manual.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "1000186310656"
                        used: "804296695808"
                email: gabrieljpanza@gmail.com
                executable: c:\Users\Gabriel Panza\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 00e5ba01553071043d6dd437c3dd24256a21d07f
                    remote: https://github.com/Gabriel-Panza/Machine-Learning-FCD.git
                host: GABS-LAPTOP
                memory:
                    total: "16889782272"
                os: Windows-10-10.0.26100-SP0
                program: d:\Documents\GitHub\Machine-Learning-FCD\New Data\SNN_Manual.ipynb
                python: CPython 3.10.11
                root: d:\Documents\GitHub\Machine-Learning-FCD\New Data
                startedAt: "2025-09-12T14:52:38.954241Z"
                writerId: mk87whbia4e9llaf4nf5scacaazxpbch
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 17
                - 19
            "4": 3.10.11
            "5": 0.21.1
            "8":
                - 1
                - 3
            "12": 0.21.1
            "13": windows-amd64
batch_size:
    value: 128
epochs:
    value: 150
learning_rate:
    value: 0.001
